config/routes.rb
Rails.application.routes.draw do
  
  root 'generators#index'
  
  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/account' => 'users#show'
  
  
  
  
  # This is the Golden 7 for Movies
  get '/generators' => 'generators#index'
  get '/generators/new' => 'generators#new'
  post '/generators' => 'generators#create'

  get '/generators/:id' => 'generators#show'
  get '/generators/:id/edit' => 'generators#edit'
  patch '/generators/:id' => 'generators#update'

  delete '/generators/:id' => 'generators#destroy'
  
  resources :users
  resources :fuels
  resources :states
  
  


end

app/models/fuel.rb
class Fuel < ActiveRecord::Base

	validates_presence_of :fueltype

end

app/models/generator.rb
class Generator < ActiveRecord::Base

  belongs_to :fuel
  belongs_to :state

  validates_presence_of :queue
  validates_presence_of :mw


end

app/models/rto.rb
class Rto < ActiveRecord::Base

  belongs_to :state
  belongs_to :generator

  # def actor
  #   Actor.find(self.actor_id)
  # end

end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :generators 

  validates_presence_of :name
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :name, :email, :password, presence: true
  validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController

  def index
    @fuels = Fuel.all
  end

  def new
  end
  
  
  def update
    fuel = Fuel.find_by(:id => params["id"])
    fuel.fueltype = params["fueltype"]
    fuel.availability = params["availability"]
    fuel.linktoimage = params["linktoimage"]
    fuel.save
    redirect_to "/fuels" 
  end
  
  
  def edit
    @fuel = Fuel.find_by(:id => params["id"])
  end


  def create
    fuel = Fuel.new
    fuel.fueltype = params["fueltype"]
    fuel.availability = params["availability"]
    fuel.linktoimage = params["linktoimage"]
    fuel.save
    
    redirect_to "/fuels" # "/"
  end

  def show
    @fuel = Fuel.find_by(:id => params["id"])
  end

  def destroy
    Fuel.delete(params[:id])
    Generator.where(:fuel_id => params[:id]).destroy_all
    redirect_to "/fuels"
  end

end

app/controllers/generators_controller.rb
class GeneratorsController < ApplicationController


  def index
    if params["keyword"].present?
      k = params["keyword"].strip
      @generators = Generator.where("queue LIKE ?", "%#{k}%")
    else
      @generators = Generator.all
    end
  end


  def new
  end
  
  
  def update
    generator = Generator.find_by(:id => params["id"])
    generator.queue = params[:queue]
    generator.project_name = params[:projectname]
    generator.mw = params[:mw]
    generator.inservice_date = params[:inservicedate]
    generator.fuel_id = params[:fuel_id]
    generator.county = params[:county]
    generator.state_id = params[:state_id]
    generator.save
    redirect_to root_url
  end
  
  
  def edit
    @generator = Generator.find_by(:id => params["id"])
  end


  def create
    generator = Generator.new
    generator.queue = params["queue"]
    generator.project_name = params["projectname"]
    generator.mw = params["mw"]
    generator.inservice_date = params["inservicedate"]
    generator.fuel_id = params["fuel_id"]
    generator.county = params["county"]
    generator.state_id = params["state_id"]
    generator.save
    
    redirect_to root_url # "/"
  end

  def show
    @generator = Generator.find_by(:id => params["id"])
  end

  def destroy
    Generator.delete(params[:id])
    redirect_to "/generators"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Thanks for Visiting Power Plant Maps!"
  end
  
  
  def create
    user = User.find_by_email(params["email"])

    if user
      if user.authenticate(params["password"])
        session[:user_id] = user.id
        flash[:notice] = "Welcome to Power Plant Maps, #{user.name}!"
        redirect_to root_url
      else
        render 'new'
      end
    else
      render 'new'
    end

  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

  def index
    @states = State.all
  end

  def new
  end
  
  
  def update
    state = State.find_by(:id => params["id"])
    state.name = params["name"]

    state.save
    redirect_to "/states" 
  end
  
  
  def edit
    @state = State.find_by(:id => params["id"])
  end


  def create
    state = State.new
    state.name = params["name"]
    state.shortname = params["shortname"]
    state.save
    
    redirect_to "/states" # "/"
  end


  def destroy
    State.delete(params[:id])

    Generator.where(:state_id => params[:id]).destroy_all
    redirect_to "/states"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
      flash[:notice] = "Thanks for signing up!"
      redirect_to generators_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]

    if @user.password.present? && @user.password == params[:password_confirmation]
      if @user.save
        flash[:notice] = "Account updated successfully."
        redirect_to user_url(@user.id)
      else
        render 'edit'
      end
    else
      @user.errors.add(:password, "does not match")
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fuels/edit.html.erb
<h1>Edit a Fuel</h1>


<%= form_tag "/fuels/#{@fuel.id}", :method => "patch" do %>
  <div>
    <label>Fuel Type :</label>
    <input type="text" name="fueltype" value="<%= @fuel.fueltype %>">
  </div>

  <div>
    <label>Availability :</label>
    <input type="text" name="availability" value="<%= @fuel.availability %>">
  </div>

  <div>
    <label>Link to Image :</label>
    <input type="text" name="linktoimage" value="<%= @fuel.linktoimage %>">
  </div>


  <input type="submit" value="Update Fuel">

<% end %>

app/views/fuels/index.html.erb
<h1> POWER PLANT FUELS </h1>

<%= link_to("Add New Fuel", "fuels/new") %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th width="30%">Fuel Type</th>
      <th width="30%"> Availability </th>
      <th></th>
      <th></th>
    </tr>
  <tbody>
    <% @fuels.each do |fuel| %>
      <tr>
        <td>
          <%= link_to fuel.fueltype, "/fuels/#{fuel.id}" %>
        </td>
        <td><%= fuel.availability %></td>

        <td><%= link_to "Delete", "/fuels/#{fuel.id}", :method => "delete" %></td>
        <td><%= link_to "Edit", "/fuels/#{fuel.id}/edit" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fuels/new.html.erb
<h1>Add a New Fuel </h1>

<%= form_tag "/fuels" do %>
  <div>
    <label>Fuel Type :</label>
    <input type="text" name="fueltype">
  </div>

  <div>
    <label>Availability :</label>
    <input type="text" name="availability">
  </div>
  
  <div>
    <label>Link to Image :</label>
    <input type="text" name="linktoimage">
  </div>

  <input type="submit" value="Add New Fuel">

<% end %>

app/views/fuels/show.html.erb
<h1> <%= @fuel.fueltype %> </h1>
<img src=<%= @fuel.linktoimage %> />

app/views/generators/edit.html.erb
<h1>Edit Generator</h1>

<%= form_tag "/generators/#{@generator.id}", :method => "patch" do %>
  <div>
    <label>Queue :</label>
    <input type="text" name="queue" value="<%= @generator.queue %>">
  </div>

  <div>
    <label>Project Name :</label>
    <input type="text" name="projectname" value="<%= @generator.project_name %>">
  </div>


  <div>
    <label>MW :</label>
    <input type="text" name="mw" value="<%= @generator.mw %>">
  </div>
  
  
  <div>
    <label>In Service Date :</label>
    <input type="text" name="inservicedate" value="<%= @generator.inservice_date %>">
  </div>
      

  <label>Fuel Type :</label>
  <select name="fuel_id">

  <% Fuel.all.each do |d| %>
      <option value="<%= d.id %>"><%= d.fueltype %></option>
    <% end %>
  </select>
    
  <div>
    <label>County :</label>
    <input type="text" name="county" value="<%= @generator.county %>">
  </div>
      
  <label>State :</label>
  <select name="state_id">
  <% State.all.each do |d| %>
      <option value="<%= d.id %>"><%= d.name %></option>
    <% end %>
  </select>
  <div>
  <input type="submit" value="Update Generator">
</div>
<% end %>

app/views/generators/index.html.erb
<%= link_to("Add New Generator", "generators/new") %>


<table class="table table-stripped">
  <thead>
    <tr>
      <th>Queue</th>
      <th>Project Name</th>
      <th>Mega Watt</th>
      <th>In Service Date</th>
      <th>Fuel Type</th>
      <th>County</th>
      <th>State</th>
      <th></th>
    </tr>  
  </thead>
 
  <tbody>
    <% @generators.each do |generator| %>
      <tr>
        <td>
          <%= link_to generator.queue, "/generators/#{generator.id}" %>
          <%= link_to "(edit)", "/generators/#{generator.id}/edit" %>
        </td>
        <td>
          <%= generator.project_name %>
        </td>
        <td>
          <%= generator.mw %>
        </td>
        <td>
          <%= generator.inservice_date %>
        </td>
        <td>
          <%= Fuel.find_by(id:generator.fuel_id).fueltype %>
          
        </td>
        <td>
          <%= generator.county %>
        </td>
        <td>
          <%= State.find_by(id:generator.state_id).shortname %>
        </td>
        
        <td>
          <%= link_to "Delete", "/generators/#{generator.id}", :method => "delete" %>
        </td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/generators/new.html.erb
<h1>Add a New Generator </h1>


<%= form_tag "/generators" do %>
  <div>
    <label>Queue :</label>
    <input type="text" name="queue">
  </div>

  <div>
    <label>Project Name :</label>
    <input type="text" name="projectname">
  </div>
  
  <div>
    <label>MW :</label>
    <input type="text" name="mw">
  </div>
  
  
  <div>
    <label>In Service Date :</label>
    <input type="text" name="inservicedate">
  </div>
    
  <label>Fuel Type :</label>
  <select name="fuel_id">

  <% Fuel.all.each do |d| %>
      <option value="<%= d.id %>"><%= d.fueltype %></option>
    <% end %>
  </select>
  
  <div>
    <label>County :</label>
    <input type="text" name="county">
  </div>
    

  <label>State :</label>
  <select name="state_id">
  <% State.all.each do |d| %>
      <option value="<%= d.id %>"><%= d.name %></option>
    <% end %>
  </select>

  <div>
  <input type="submit" value="Add Generator">
</div>
<% end %>

app/views/generators/show.html.erb
<h1>Generator Queue : <%= @generator.queue%></h1>
<p>This is a <%= @generator.project_name%> project. It has a capacity of <%= @generator.mw%>MW. It is going to be located
in <%= @generator.county%> County, <%= @generator.state.name%>.
It is going to be powered by <%= @generator.fuel.fueltype%> and in service by <%= @generator.inservice_date%></p>


<h3> More about the project to come ..... PAGE UNDER CONSTRUCTION </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Future Generators</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js' %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" %>

  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Future Power Plants</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/states">States</a></li>
          <li><a href="/fuels">Fuel</a></li>


          <form action="/generators" class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input value="<%= params[:keyword] %>" name="keyword" type="text" class="form-control" placeholder="Queue">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if session[:user_id] %>
            <li><a  href="/account">Hi <%= User.find(session[:user_id]).name %> ! </a></li>
            <li><a href="/logout">Sign Out</a></li>
          <% else %>
          <li><a href="/users/new">Sign Up</a></li>
          <li><a href="/sessions/new">Sign In</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

    <% if flash[:notice].present? %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/states/edit.html.erb
<h1>Edit a State</h1>


<%= form_tag "/states/#{@state.id}", :method => "patch" do %>
  <div>
    <label>State Name :</label>
    <input type="text" name="name" value="<%= @state.name %>">
  </div>

  <div>
    <label>State Short Name :</label>
    <input type="text" name="shortname" value="<%= @state.shortname %>">
  </div>


  <input type="submit" value="Update State">

<% end %>

app/views/states/index.html.erb
<h1>STATES </h1>

<%= link_to("Add New State", "states/new") %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th width="30%">State Name</th>
      <th width="30%"> Number of Generators </th>
      <th></th>
      <th></th>
    </tr>
  <tbody>
    <% @states.each do |state| %>
      <tr>

        <td><%= state.name %></td>
        <td><%= Generator.where(state_id:state.id).count %></td>          

        <td><%= link_to "Delete", "/states/#{state.id}", :method => "delete" %></td>
        <td><%= link_to "Edit", "/states/#{state.id}/edit" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/states/new.html.erb
<h1>Add a New State </h1>

<%= form_tag "/states" do %>
  <div>
    <label>State Type :</label>
    <input type="text" name="name">
  </div>

  <div>
    <label>Short Name :</label>
    <input type="text" name="shortname">
  </div>


  <input type="submit" value="Add New State">

<% end %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>User Accounts</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Name</td>
      <td>Email Address</td>
      <td>Password</td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign Up</h1>
</div>

<% if @user.errors.any? %>
  <ul class="list-unstyled text-danger">
    <% @user.errors.full_messages.each do |msg| %>
      <li><strong><%= msg %></strong></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag users_path do %>

  <p>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </p>

  <p>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </p>

  <p>
    <%= label_tag :password_confirmation, "Password Again" %>
    <%= password_field_tag :password_confirmation %>
  </p>

  <%= submit_tag "Sign Me Up!" %>

<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to "Edit", edit_user_path(@user.id), class: 'btn btn-md btn-primary pull-right' %>
  <h1>My Account</h1>
</div>


<p>
  <strong>Name:</strong> <%= @user.name %>
</p>

<p>
  <strong>Email address on file:</strong> <%= @user.email %>
</p>

<p>
  <strong>Current password:</strong> <%= @user.password %>
</p>